apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Моя страница</title>
    </head>
    <body>
        <h1>Добро пожаловать на мою страницу!</h1>
        <p>Это статическая страница</p>
    </body>
    </html>
