{
 "title": "Dashboard hw 5-3",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Загрузка CPU за 15 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Загрузка CPU за 5 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_load5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Загрузка CPU за 1 минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Утилизация CPU (в процентах)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)\n"
    },
    {
     "expr": "node_load1{instance=\"node_exporter:9100\"}"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Количество свободной оперативной памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свободное место на файловой системе",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "CPULA15",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load15{}" }
   ]
  },
  {
   "title": "CPULA1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1{}" }
   ]
  },
  {
   "title": "CPULA5",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5{}" }
   ]
  },
  {
   "title": "Свободная оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes{}" }
   ]
  }
 ]
}