apiVersion: v1
kind: Service
metadata:
  name: multi-container-nodeport
spec:
  selector:
    app: multi-container-app
  type: NodePort
  ports:
    - name: nginx80
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: nginx8080
      port: 8080
      targetPort: 8080
      nodePort: 30088
  

