apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-read-syslog
  namespace: volume
spec:
  selector:
    matchLabels:
      app: multitool-read-syslog
  template:
    metadata:
      labels:
        app: multitool-read-syslog
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "/host/var/log/syslog..."
            tail -f /host/var/log/syslog
        volumeMounts:
        - name: host-logs
          mountPath: /host/var/log/syslog
          subPath: syslog
          readOnly: true
      volumes:
      - name: host-logs
        hostPath:
          path: /var/log
          type: Directory


