global:
  namespace: default

frontend:
  replicaCount: 1
  image:
    repository: nginx
    tag: "1.23.4"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1
  image:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
