global:
  namespace: app2

frontend:
  replicaCount: 1
  image:
    repository: nginx
    tag: "1.23.4"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP

backend:
  replicaCount: 1
  image:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
