---
- name: Install Nginx
  hosts: lighthouse-01
  become: true
  tasks:
    - name: Nginx | Install epel-release
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Nginx | Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Nginx | Create config
      ansible.builtin.template:
        src: ./templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify: restart-nginx
  handlers:
    - name: restart-nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: Install Lighthouse
  hosts: lighthouse-01
  handlers:
    - name: restart-nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      become: true
      become_method: sudo

  pre_tasks:
    - name: Lighthouse | Install Dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present

  tasks:
    - name: Create Lighthouse directory
      become: true
      ansible.builtin.file:
        path: /var/www/lighthouse
        state: directory
        recurse: yes
        mode: '0755'
        owner: nginx
        group: nginx

    - name: Ensure /var/www/lighthouse is added to Git safe.directory
      ansible.builtin.command:
        cmd: git config --global --add safe.directory /var/www/lighthouse
      environment:
        HOME: "/root"

    - name: Reset local changes in the repository
      ansible.builtin.command:
        cmd: git reset --hard
        chdir: /var/www/lighthouse

    - name: Lighthouse | Clone from Git
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ lighthouse_location_dir }}"
    - name: Lighthouse | Create lighthouse config
      become: true
      ansible.builtin.template:
        src: ./templates/lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: '0644'
      notify: restart-nginx
  tags: Lighthouse

- name: Install Clickhouse
  hosts: clickhouse-01
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - name: Mess with clickhouse distrib
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{item}}-{{clickhouse_version}}.x86_64.rpm"
            dest: "/tmp/{{item}}-{{clickhouse_version}}.rpm"
            mode: "0644"
          with_items: "{{ clickhouse_packages }}"

      rescue:
        - name: Get clickhouse distrib (rescue)
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{clickhouse_version}}.x86_64.rpm"
            dest: "/tmp/clickhouse-common-static-{{clickhouse_version}}.rpm"
            mode: "0644"

    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - /tmp/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm
          - /tmp/clickhouse-client-{{ clickhouse_version }}.x86_64.rpm
          - /tmp/clickhouse-server-{{ clickhouse_version }}.x86_64.rpm
        disable_gpg_check: true
      notify: Start clickhouse service
    - name: Flush handlers to restart clickhouse
      ansible.builtin.meta: flush_handlers

- name: Install vector
  hosts: vector-01
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "/tmp/vector-{{ vector_version }}.rpm"
        mode: "0644"
      notify: Start vector service

    - name: Install vector packages
      become: true
      ansible.builtin.yum:
        name:
          - /tmp/vector-{{ vector_version }}-1.x86_64.rpm
        disable_gpg_check: true
    - name: Flush handlers to restart vector
      ansible.builtin.meta: flush_handlers

    - name: Configure Vector | ensure what directory exists
      ansible.builtin.file:
        path: "{{ vector_config_dir }}"
        state: directory
        mode: "0755"

    - name: Configure Vector | Template config
      ansible.builtin.template:
        src: "./templates/vector.yml.j2"
        dest: "{{ vector_config_dir }}/vector.yml"
        mode: "0644"
