---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install vector
  hosts: vector
  roles:
    - vector
    
- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - lighthouse
