apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-logs-and-describe-pods
  namespace: default
subjects:
- kind: User
  name: kubuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view-logs-and-describe-pods
  apiGroup: rbac.authorization.k8s.io